import {e} from './feedback-ui';
import {feedbackRequestAction} from './project-requests';
import {attemptChoices,helpfulChoices,priceChoices,focusChoices} from './feedback-policy.mjs';
const count=(p:any,key:string)=>{const v=p[key];return Number((Array.isArray(v)?v[0]:v)?.count)||0;};
export const OWNED_CARD_FIELDS='id,slug,title,category,listing_status,preview_public_url,preview_path,lock_version,is_studio,published_at,updated_at,saved_projects(count),project_experiences(count),creator_feedback(count)';
export const shortStatus=(status:string)=>({draft:'Draft',in_review:'In review',published:'Published',unpublished:'Unpublished'}[status]||status);
export function miniPreview(p:any){const src=p.preview_public_url||(p.is_studio?p.preview_path:'');return src?`<img class="mini-preview" src="${e(src)}" alt="${e(p.title||'Project')} preview" loading="lazy">`:`<span class="mini-preview preview-placeholder" aria-label="No preview yet">${e((p.title||'?').slice(0,1))}</span>`;}
export function projectActions(p:any){return `<details class="project-actions"><summary aria-label="Actions for ${e(p.title||'project')}">⋯</summary><div class="project-action-menu"><a href="/dashboard/project?slug=${e(p.slug)}" data-panel>View project</a><button type="button" data-invite-project="${e(p.slug)}">Invite testers</button>${feedbackRequestAction(p)}<a href="/?listing=settings&amp;project=${e(p.slug)}">Edit listing</a><a href="/dashboard/builds?project=${e(p.slug)}">Builds & release notes</a><a href="/dashboard/messages?project=${encodeURIComponent(p.title)}">Messages</a>${p.listing_status==='published'||p.listing_status==='in_review'?`<button type="button" data-project-action="unpublish" data-id="${e(p.id)}">${p.listing_status==='published'?'Unpublish':'Withdraw from review'}</button>`:'<a href="/?listing=settings&amp;project='+e(p.slug)+'">Review publishing options</a>'}${p.listing_status==='draft'&&!p.is_studio&&!p.published_at?`<button type="button" class="danger-action" data-project-action="delete" data-id="${e(p.id)}" data-version="${p.lock_version}">Delete draft…</button>`:''}</div></details>`;}
export function ownedProjectCard(p:any,unread:number|null){return `<article class="owned-project-card" data-project-card><div class="owned-project-top">${miniPreview(p)}<div><h2><a href="/dashboard/project?slug=${e(p.slug)}" data-panel>${e(p.title||'Untitled draft')}</a></h2><span class="project-status ${e(p.listing_status)}">${e(shortStatus(p.listing_status))}</span></div>${projectActions(p)}</div><div class="project-counts"><span>${count(p,'saved_projects')} saves</span><span>${count(p,'project_experiences')+count(p,'creator_feedback')} comments & reviews</span><a href="/dashboard/messages?project=${encodeURIComponent(p.title)}&amp;unread=1">${unread===null?'Unread unavailable':unread+' unread conversations'}</a></div><p data-project-action-status role="status"></p></article>`;}
export function performancePanel(projects:any[],total:number){return `<section class="cw-panel"><h2>Project performance</h2><div class="table-scroll"><table class="performance-table"><thead><tr><th>Project</th><th>Visits</th><th>Comments & reviews</th><th>Saved</th><th>Shared</th></tr></thead><tbody>${projects.map(p=>`<tr><td><a data-panel href="/dashboard/project?slug=${e(p.slug)}">${e(p.title||'Untitled draft')}</a></td><td class="metric-unavailable">Not tracked</td><td>${count(p,'project_experiences')+count(p,'creator_feedback')}</td><td>${count(p,'saved_projects')}</td><td class="metric-unavailable">Not tracked</td></tr>`).join('')}</tbody></table></div>${projects.length?'':'<p>Add your first project to see its activity here.</p>'}<p class="metric-note">All-time comment/review records, including those awaiting moderation; current saves. Per-project visits and completed shares are not recorded. Your personal category browsing is not included.</p>${total>projects.length?`<a href="/dashboard?view=creator">View all ${total} projects →</a>`:''}</section>`;}
export function replyComposer(id:string,requestId:string){return `<form class="inline-composer" data-inline-compose action="/api/feedback-reply" method="post"><input type="hidden" name="id" value="${e(id)}"><input type="hidden" name="requestId" value="${e(requestId)}"><div class="compose-field"><label class="visually-hidden" for="reply-${e(id)}">Your reply</label><textarea id="reply-${e(id)}" name="message" required maxlength="800" rows="2" placeholder="Write a thoughtful reply…" aria-describedby="reply-count-${e(id)}"></textarea><button type="submit" class="send-arrow" aria-label="Send reply" hidden>➤</button></div><small data-inline-count id="reply-count-${e(id)}" hidden>0 / 7–150 words</small><p class="comment-conduct">Be thoughtful. Be respectful. <a href="/community-guidelines">Guidelines</a></p><p data-inline-status role="status"></p></form>`;}
const select=(name:string,label:string,options:Record<string,string>)=>`<label>${label}<select name="${name}" required><option value="">Choose…</option>${Object.entries(options).map(([v,l])=>`<option value="${v}">${e(l)}</option>`).join('')}</select></label>`;
export function savedReviewComposer(p:any){return `<p class="review-credit-hint">Try this project and leave a helpful review to earn 1 credit.</p><details class="inline-help"><summary aria-label="Review credit rules">?</summary><p>Saving alone earns no credit. A qualifying firsthand review earns one base credit; duplicates, self-reviews and ordinary replies do not. Public reviews require moderation. <a href="/dashboard/community#credit-rules">Credit rules</a></p></details><form class="inline-composer" data-inline-compose action="/api/feedback" method="post"><input type="hidden" name="slug" value="${e(p.slug)}"><div class="compose-field"><label class="visually-hidden" for="saved-review-${e(p.slug)}">Review ${e(p.title)}</label><textarea name="message" id="saved-review-${e(p.slug)}" maxlength="800" required rows="2" placeholder="What did you try? What helped, or could be improved?" aria-describedby="saved-count-${e(p.slug)}"></textarea><button type="submit" class="send-arrow" aria-label="Send review" hidden>➤</button></div><small data-inline-count id="saved-count-${e(p.slug)}" hidden>0 / 7–150 words</small><details class="review-options-details"><summary>Review details · required before sending</summary><div class="review-options">${select('attempt','What did you try?',attemptChoices)}${select('helpful','Did it help?',helpfulChoices)}${select('price','How did the price feel?',priceChoices)}${select('focus','Your feedback is about',focusChoices)}<label>Who can see this?<select name="visibility"><option value="private">Me and the creator</option><option value="public">Community, after review</option></select></label></div></details><p data-inline-status role="status"></p></form>`;}
