import { htmlEscape as e } from './admin';
import { helpfulChoices, priceChoices, attemptChoices, focusChoices } from './feedback-policy.mjs';
export { e };
export function surface(title:string,body:string,active='',status=200,isAdmin=false) {
 const items=[['overview','/dashboard/overview','Overview'],['creator','/dashboard?view=creator','My projects'],['messages','/dashboard/messages','Messages'],['visitor','/dashboard?view=visitor','Saved apps'],['profile','/dashboard/profile','Public profile'],['security','/dashboard/security','Account & security'],['notifications','/dashboard/notifications','Notifications'],['privacy','/dashboard/privacy','Privacy & data'],['preferences','/dashboard/preferences','Preferences'],['help','/dashboard/help','Help & contact']];
 const workspace = items.some(([key])=>key===active);
 const sidebar = `<aside class="cw-sidebar"><p class="eyebrow">My dashboard</p><details class="cw-dashboard-menu" open><summary>Dashboard menu</summary><nav aria-label="Dashboard sections">${items.map(([key,url,label])=>`<a href="${url}" ${active===key?'aria-current="page"':''}>${label}</a>`).join('')}${isAdmin?'<a href="/admin/workspace">Administration</a>':''}</nav></details></aside>`;
 return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex"><title>${e(title)} · TryMyBuild</title><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/feedback.css"><link rel="stylesheet" href="/launch-refinements.css"><link rel="stylesheet" href="/ui-refinements.css"><link rel="stylesheet" href="/future-design.css"><link rel="icon" type="image/svg+xml" href="/assets/brand/trymybuild-favicon.svg"><link rel="apple-touch-icon" sizes="180x180" href="/assets/brand/trymybuild-app-180.png"></head><body class="cw-workspace"><a class="skip-link" href="#main-content">Skip to content</a><header class="cw-bar"><a href="/" class="cw-brand"><img class="brand-mark" src="/assets/brand/trymybuild-mark.svg" width="40" height="40" alt=""><span class="brand-name">TryMy<span class="brand-name-works">Build</span></span><span class="brand-promise">Discover apps. Share your app.</span></a><nav aria-label="Website navigation"><a href="/">Explore apps</a><a href="/?listing=settings" data-guest-listing>Share your app</a><a href="/dashboard" data-account-nav aria-label="My account">My account</a></nav></header><main id="main-content" tabindex="-1" class="cw-main ${workspace ? "cw-dashboard-layout" : ""}">${workspace ? sidebar : ""}<div class="cw-dashboard-content">${body}</div></main><footer class="cw-legal-footer"><a href="/terms">Terms of Service</a><a href="/privacy">Privacy Policy</a><a href="/community-guidelines">Community Guidelines</a><a href="/?page=contact">Contact</a></footer><script src="/interaction-polish.js" defer></script><script src="/workspace-ui.js" defer></script><script src="/project-media.js" defer></script><script src="/public-comments.js" defer></script><script src="/return-preferences.js" defer></script><script src="/project-actions.js" defer></script><script src="/community-input.js" defer></script><script src="/share-invitation.js" defer></script><script src="/notification-bell.js" defer></script><script src="/account-nav.js" defer></script></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store','X-Robots-Tag':'noindex'}});
}
export const unavailable = () => surface('A little more setup is needed','<section class="cw-panel"><h1>A little more setup is needed.</h1><p>This part of TryMyBuild isn’t ready right now. Nothing has been sent or changed.</p><a href="/dashboard">Return to my dashboard</a></section>','',503);
export const signIn = (next:string) => surface('Your TryMyBuild',`<section class="cw-panel"><p class="eyebrow">One account. Both sides.</p><h1>Keep the conversation going.</h1><p>Sign in to see your saved projects, feedback, and creator replies.</p><a class="primary-button" href="/auth/sign-in?next=${encodeURIComponent(next)}">Sign in</a></section>`,'',401);
export function signals(item:any) { return `<div class="cw-signals">${item.attempt?`<span>${e(attemptChoices[item.attempt as keyof typeof attemptChoices])}</span>`:''}${item.focus?`<span>${e(focusChoices[item.focus as keyof typeof focusChoices])}</span>`:''}<span>${e(helpfulChoices[item.helpful as keyof typeof helpfulChoices])}</span><span>${e(priceChoices[item.price as keyof typeof priceChoices])}</span></div>`; }
export function feedbackCard(item:any,title:string,author:string,thread=true,avatar='') {
 return `<article class="cw-panel"><div class="cw-row"><h3>${e(title)}</h3><span class="cw-meta">${item.visibility==='private'?'Private feedback':item.moderation_status==='published'?'Public feedback':item.moderation_status==='hidden'?'Not publicly visible':'Awaiting public review'}</span></div><p class="cw-meta">${avatar?`<span class="person-avatar"><img src="${e(avatar)}" alt=""></span>`:''}${e(author)} · ${e(new Date(item.created_at).toLocaleDateString('en-US'))} · Self-reported experience</p>${signals(item)}${item.message?`<p class="cw-message">${e(item.message)}</p>`:''}${thread?`<a class="cw-link" href="/dashboard/messages?thread=${e(item.id)}">Open conversation →</a>`:''}</article>`;
}
export function pages(path:string,page:number,count:number) { return `<nav class="cw-row" aria-label="Pages">${page?`<a href="${e(path)}&page=${page-1}">← Previous</a>`:''}<span class="cw-meta">${count} total</span>${(page+1)*25<count?`<a href="${e(path)}&page=${page+1}">Next →</a>`:''}</nav>`; }
export const pageNumber = (value:string|null) => value && /^\d{1,5}$/.test(value) ? Number(value) : 0;

export function adminNavigation(active:string) {
 const links=[['overview','/admin/workspace','Overview'],['people','/admin/workspace?tab=people','People & verification'],['projects','/admin?section=projects','Project review'],['comments','/admin?section=comments','Community comments'],['community','/admin/community','Community credits & discussion'],['feedback','/admin/feedback','Creator feedback review'],['cases','/admin/workspace?tab=cases','Support & reports'],['privacy','/admin/workspace?tab=privacy','Privacy requests'],['activity','/admin/workspace?tab=activity','Activity'],['settings','/admin/workspace?tab=settings','Site & analytics']];
 return '<nav class="cw-admin-nav" aria-label="Administration">'+links.map(([key,url,label])=>`<a href="${url}" ${key===active?'aria-current="page"':''}>${label}</a>`).join('')+'</nav>';
}
export function adminSurface(title:string,body:string,active:string,status=200) {
 return surface(title,`<div class="cw-admin-layout">${adminNavigation(active)}<div class="cw-admin-content admin-shell">${body}</div></div>`,'overview',status,true);
}
