import {e} from './feedback-ui';

export function exchangeStatus(entry:any){
 if(!entry)return '';
 const active=['waiting','matched'].includes(entry.state);
 const leave=active&&!entry.complete?`<form method="post" action="/api/maker-exchange"><input type="hidden" name="action" value="leave"><input type="hidden" name="id" value="${e(entry.id)}"><button class="secondary-button">Leave this exchange</button><p class="cw-meta">This ends the pair and cancels any open requests for this exchange. Feedback already shared stays in Messages.</p></form>`:'';
 if(entry.state==='waiting')return `<section class="cw-panel"><h2>Waiting for another maker</h2><p>You’re in the exchange. We’ll notify you in TryMyBuild when another participating maker is matched with you. Email follows your feedback alert settings.</p><p>There may not be another maker available yet. There’s no promised match or response time.</p>${leave}</section>`;
 if(!active)return `<section class="cw-panel"><h2>${entry.state==='closed'&&entry.complete?'Previous exchange completed':'This exchange ended'}</h2><p>Feedback already shared stays in Messages. You can join a new exchange below.</p></section>`;
 const peer=entry.partner;
 if(!peer)return `<section class="cw-panel"><h2>Your partner’s app is unavailable</h2><p>Leave this exchange to join another one. Your existing conversations are preserved.</p>${leave}</section>`;
 return `<section class="cw-panel"><p class="eyebrow">Maker feedback exchange</p><h2>${entry.complete?'You both shared feedback':`You’re paired with ${e(peer.maker)}`}</h2><p>You each agreed to try the other person’s app and share a firsthand observation. Honest criticism is welcome; a positive review isn’t required.</p><div class="maker-exchange-columns"><section><h3>Your feedback for ${e(peer.title)}</h3><dl><div><dt>Try this</dt><dd>${e(peer.task||'Try the main feature and notice what happens.')}</dd></div><div><dt>The maker wants to know</dt><dd>${e(peer.question)}</dd></div></dl>${entry.given?`<p>Feedback shared.</p><a class="secondary-button" href="/dashboard/messages?thread=${e(entry.given)}">Open your feedback</a>`:`<a class="primary-button" href="/projects/${e(peer.slug)}">Try their app</a><p><a href="/tell/${e(peer.slug)}">Share what happened</a></p><p class="cw-meta">A specific firsthand review counts once it meets the feedback guidelines. A pending or removed review won’t mark this step complete.</p>`}</section><section><h3>Feedback on your app</h3>${entry.received?`<p>Your partner shared feedback.</p><a class="primary-button" href="/dashboard/messages?thread=${e(entry.received)}">Read and reply</a><p>You can use “Recognize this feedback” in the conversation to explain whether it helped.</p>`:'<p>Your partner hasn’t shared qualifying feedback yet. Your own response does not guarantee theirs.</p>'}</section></div>${entry.complete?'<p>You can join another exchange below. These responses are recorded; they don’t establish that either maker found the feedback useful.</p>':leave}</section>`;
}

export function exchangeJoinForm(projects:any[],request:any,id:string){
 if(!projects.length)return '<section class="cw-panel"><h2>Share your app first</h2><p>The exchange is for makers with a published app. Listing is available without joining.</p><a class="primary-button" href="/?listing=settings">Share your app</a></section>';
 const choices=request?projects.filter(p=>p.slug===request.project_slug):projects;
 if(!choices.length)return '<section class="cw-panel"><p>Your open request belongs to an unavailable project. Manage it in My projects before joining an exchange.</p><a href="/dashboard?view=creator">My projects</a></section>';
 return `<section class="cw-panel"><h2>Join the maker feedback exchange</h2><p>Get paired with another participating maker. Try their app and answer their question; they agree to do the same for yours.</p><form method="post" action="/api/maker-exchange"><input type="hidden" name="action" value="join"><input type="hidden" name="id" value="${e(request?.id||id)}"><label for="exchange-project">Your published app</label><select id="exchange-project" name="slug" required>${choices.map(p=>`<option value="${e(p.slug)}">${e(p.title)}</option>`).join('')}</select><label for="exchange-question">One thing you want to learn</label><textarea id="exchange-question" name="question" minlength="10" maxlength="300" required ${request?'readonly':''} placeholder="Was it clear how to save your first plan?">${e(request?.question||'')}</textarea><p class="cw-meta">${request?'This uses your existing open feedback request.':'Your question will be visible on your app’s feedback brief.'} Don’t include private information.</p><label class="legal-agreement"><input type="checkbox" name="exchangeCommitment" required><span>I’ll personally try the other maker’s app and share what I observed.</span></label><label class="legal-agreement"><input type="checkbox" name="responseCommitment" required><span>I’ll reply to feedback on my app.</span></label><p>One exchange at a time. Participation is optional, with no credit charge. A match or response isn’t guaranteed. You can leave at any time.</p><button class="primary-button">Join the exchange</button></form></section>`;
}
