import {e} from './feedback-ui';

export function exchangeStatus(entry:any){
 if(!entry)return '';
 const active=['waiting','matched'].includes(entry.state);
 const leave=active&&!entry.complete?`<form method="post" action="/api/maker-exchange"><input type="hidden" name="action" value="leave"><input type="hidden" name="id" value="${e(entry.id)}"><button class="secondary-button">Leave this exchange</button><p class="cw-meta">This ends the pair and cancels any open requests for this exchange. Feedback already shared stays in Messages.</p></form>`:'';
 if(entry.state==='waiting')return `<section class="cw-panel"><h2>Waiting for a feedback partner</h2><p>We’ll notify you when we pair you with another app creator. You’ll try their app, and they’ll agree to try yours. Email follows your feedback alert settings.</p><p>There may not be another maker available yet. There’s no promised match or response time.</p>${leave}</section>`;
 if(!active)return `<section class="cw-panel"><h2>${entry.state==='closed'&&entry.complete?'Previous exchange completed':'This exchange ended'}</h2><p>Feedback already shared stays in Messages. You can join a new exchange below.</p></section>`;
 const peer=entry.partner;
 if(!peer)return `<section class="cw-panel"><h2>Your partner’s app is unavailable</h2><p>Leave this exchange to join another one. Your existing conversations are preserved.</p>${leave}</section>`;
 return `<section class="cw-panel"><p class="eyebrow">App feedback swap</p><h2>${entry.complete?'You both shared feedback':`You’re paired with ${e(peer.maker)}`}</h2><p>You try their app and tell them what you noticed. They agreed to do the same for yours. You don’t have to give a positive review.</p><div class="maker-exchange-columns"><section><h3>Your feedback for ${e(peer.title)}</h3><dl><div><dt>Try this</dt><dd>${e(peer.task||'Try the main feature and notice what happens.')}</dd></div><div><dt>The maker wants to know</dt><dd>${e(peer.question)}</dd></div></dl>${entry.given?`<p>Feedback shared.</p><a class="secondary-button" href="/dashboard/messages?thread=${e(entry.given)}">Open your feedback</a>`:`<a class="primary-button" href="/projects/${e(peer.slug)}">Try their app</a><p><a href="/tell/${e(peer.slug)}">Share what happened</a></p><p class="cw-meta">A specific firsthand review counts once it meets the feedback guidelines. A pending or removed review won’t mark this step complete.</p>`}</section><section><h3>Feedback on your app</h3>${entry.received?`<p>Your partner shared feedback.</p><a class="primary-button" href="/dashboard/messages?thread=${e(entry.received)}">Read and reply</a><p>You can use “Recognize this feedback” in the conversation to explain whether it helped.</p>`:'<p>You’re still waiting for feedback from your partner. Sharing yours doesn’t guarantee they’ll respond.</p>'}</section></div>${entry.complete?'<p>You both shared feedback. You can start another swap below.</p>':leave}</section>`;
}

export function exchangeJoinForm(projects:any[],request:any,id:string){
 if(!projects.length)return '<section class="cw-panel"><h2>Share your app first</h2><p>Publish your app, then come back to swap feedback with another app creator. Joining the swap is optional.</p><a class="primary-button" href="/?listing=settings">Share your app</a></section>';
 const choices=request?projects.filter(p=>p.slug===request.project_slug):projects;
 if(!choices.length)return '<section class="cw-panel"><p>Your open request belongs to an unavailable project. Manage it in My projects before joining an exchange.</p><a href="/dashboard?view=creator">My projects</a></section>';
 return `<section class="cw-panel"><h2>You try their app. They try yours.</h2><ol><li>Choose your app and ask one question about it.</li><li>We pair you with another app creator who wants feedback.</li><li>You each try the other’s app and share what you noticed.</li></ol><form method="post" action="/api/maker-exchange"><input type="hidden" name="action" value="join"><input type="hidden" name="id" value="${e(request?.id||id)}"><label for="exchange-project">Which app do you want feedback on?</label><select id="exchange-project" name="slug" required>${choices.map(p=>`<option value="${e(p.slug)}">${e(p.title)}</option>`).join('')}</select><label for="exchange-question">What should your partner look at?</label><textarea id="exchange-question" name="question" minlength="10" maxlength="300" required ${request?'readonly':''} placeholder="Example: Is it clear how to save your first plan?">${e(request?.question||'')}</textarea><p class="cw-meta">${request?'This uses your existing open feedback request.':'Your partner will see this question. It will also appear on your app’s feedback page.'} Don’t include private information.</p><label class="legal-agreement"><input type="checkbox" name="exchangeCommitment" required><span>I’ll try my partner’s app myself and give them feedback.</span></label><label class="legal-agreement"><input type="checkbox" name="responseCommitment" required><span>I’ll reply when my partner gives me feedback.</span></label><p>Free and optional. One partner at a time. If no partner is available, you’ll wait for a match. A match or reply isn’t guaranteed. You can leave at any time.</p><button class="primary-button">Find a feedback partner</button></form></section>`;
}
