import type { APIRoute } from 'astro';
import {listPublished,STUDIO,studioNote} from './catalog-db';
import {projectCard} from './project-ui';
import {database,databaseReady,ensureMember} from './database';
import {currentUser} from './auth';
import {surface,e,signIn} from './feedback-ui';
import {publicProfile} from './public-profile';
import {directComposer} from './direct-messages';
export const profileView:APIRoute=async context=>{
 if(!databaseReady())return surface('Profile unavailable','<p>Profiles are temporarily unavailable.</p>','',503);
 try{
  const db=database(),slug=context.params.slug||'',self=slug==='me',studio=slug===STUDIO.slug;let person:any,ownerId='';
  if(studio){person=await publicProfile(db,slug);person.identity_label=STUDIO.label;ownerId=person.user_id;}
  else if(self){const user=await currentUser(context);if(!user)return signIn('/people/me');const member=await ensureMember(user);
   const r=await db.from('profiles').select('user_id,slug,display_name,identity_label,bio,avatar_path,website,creator_type,location,location_public,verified,is_public').eq('user_id',member.id).maybeSingle();if(r.error)throw r.error;person=r.data;ownerId=member.id;if(person?.verified){const badge=await db.rpc('cw_badge_progress',{p_user:member.id});if(badge.error)throw badge.error;const b=badge.data?.[0];person.verified=!!b?.verified&&Number(b.reviews)>=5&&Number(b.creators)>=3&&b.ownership_confirmed&&person.creator_type!=='company';}}
  else{person=await publicProfile(db,slug);ownerId=person?.user_id||'';}
  if(!person)return surface('Profile not found','<p>This member has not made a public profile available.</p>','',404);
  const owned=studio?null:await db.from('projects').select('slug').eq('owner_user_id',ownerId).eq('listing_status','published');if(owned?.error)throw owned.error;
  const slugs=new Set(owned?.data?.map(p=>p.slug)||[]),projects=(await listPublished()).filter(p=>studio?p.creator.slug===STUDIO.slug:slugs.has(p.slug));
  const initials=person.display_name.split(/\s+/).slice(0,2).map((part:string)=>part[0]).join('');
  const user=await currentUser(context),viewer=user?await ensureMember(user):null,canonical=studio?STUDIO.slug:person.slug;
  const tools=`<div class="profile-tools">${person.is_public?`<button type="button" class="secondary-button" data-share-profile="${e(canonical)}">Share profile</button>`:'<span class="cw-meta">Make your profile public before sharing it.</span>'}</div>`;
  const message=viewer?.id===ownerId?'':`<details class="cw-panel direct-message-entry"><summary>Message this creator</summary>${viewer?directComposer(canonical):`<p>Sign in to send a private message. Your conversation stays in Messages.</p><a class="primary-button" href="/auth/sign-in?next=${encodeURIComponent('/people/'+canonical)}">Sign in to message</a>`}</details>`;
  const stats=`<section class="cw-panel profile-statistics"><h2>Public project activity</h2><div class="workspace-summary"><div><strong>${projects.length}</strong><span>Published projects</span></div><div><strong>${projects.reduce((n,p)=>n+p.reviewCount,0)}</strong><span>Published comments & reviews</span></div><div><strong>${projects.reduce((n,p)=>n+p.saveCount,0)}</strong><span>Current saves</span></div></div><details><summary>By project</summary><div class="table-scroll"><table class="performance-table"><thead><tr><th>Project</th><th>Public comments</th><th>Saved</th></tr></thead><tbody>${projects.map(p=>`<tr><td><a href="/projects/${e(p.slug)}">${e(p.name)}</a></td><td>${p.reviewCount}</td><td>${p.saveCount}</td></tr>`).join('')}</tbody></table></div></details><p class="cw-meta">Published projects and approved public contributions only. Visits and shares aren’t tracked.</p></section>`;
  const tabs=[['projects','Projects'],['activity','Activity'],['about','About'],...(message?[['message','Message']]:[])];
  return surface(person.display_name,`<article class="creator-profile-card" data-panel-content data-profile-slug="${e(canonical)}"><section class="profile-hero"><span class="person-avatar large">${person.avatar_path?`<img src="${e(person.avatar_path)}" alt="">`:e(initials)}</span><div><p class="eyebrow">${self&&!person.is_public?'Your private profile preview':'TryMyBuild creator'}</p><h1>${e(person.display_name)}</h1>${person.verified?`<span class="creator-verified" title="${e(studio?studioNote:'Qualifying contribution and app ownership confirmed')}">✓ Verified Creator</span>`:''}<strong>${e(person.identity_label||'')}</strong>${person.location_public&&person.location?`<p class="profile-location">⌖ ${e(person.location)}</p>`:''}<p>${e(person.bio||'')}</p></div></section>${tools}<div class="profile-tabs" role="tablist" aria-label="Creator profile">${tabs.map(([key,label],i)=>`<button type="button" role="tab" id="profile-tab-${e(canonical)}-${key}" aria-controls="profile-pane-${e(canonical)}-${key}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-profile-tab="${key}">${label}</button>`).join('')}</div><section role="tabpanel" aria-labelledby="profile-tab-${e(canonical)}-projects" id="profile-pane-${e(canonical)}-projects" data-profile-pane="projects" class="profile-work"><h2>Published projects · ${projects.length}</h2>${projects.map(projectCard).join('')||'<p>No published projects yet.</p>'}</section><section role="tabpanel" aria-labelledby="profile-tab-${e(canonical)}-activity" id="profile-pane-${e(canonical)}-activity" data-profile-pane="activity" hidden>${stats}</section><section role="tabpanel" aria-labelledby="profile-tab-${e(canonical)}-about" id="profile-pane-${e(canonical)}-about" data-profile-pane="about" hidden><h2>About this creator</h2><p>${e(person.bio||'')}</p>${studio?`<p class="cw-meta">${e(studioNote)}</p>`:person.verified?'<p>Verified Creator: qualifying contribution and app ownership confirmed. This does not guarantee app quality.</p>':''}${person.website?`<a href="${e(person.website)}" target="_blank" rel="noopener noreferrer nofollow">Website ↗</a>`:''}${self?'<p><a class="secondary-button" href="/dashboard/profile">Edit my profile</a></p>':''}</section>${message?`<section role="tabpanel" aria-labelledby="profile-tab-${e(canonical)}-message" id="profile-pane-${e(canonical)}-message" data-profile-pane="message" hidden>${message}</section>`:''}</article>`);
 }catch{return surface('Profile unavailable','<p>The profile could not be loaded. Please try again.</p>','',503);}
};
