import { e } from './feedback-ui';
export function projectCard(p:any){return `<article class="public-project-card"><a class="public-project-image" href="/projects/${encodeURIComponent(p.slug)}"><img src="${e(p.preview)}" alt="Preview of ${e(p.name)}" loading="lazy"></a><div class="public-project-copy"><p class="cw-meta">${e(p.category)} · ${e(p.stage)}</p><h3><a href="/projects/${encodeURIComponent(p.slug)}">${e(p.name)}</a></h3><p>${e(p.summary)}</p><p class="public-builder">${p.creator.avatar?`<img src="${e(p.creator.avatar)}" alt="">`:''}<strong>${e(p.creator.name)}</strong>${p.creator.verified?`<span class="creator-verified" title="${e(p.creator.verificationNote||'Qualifying contribution and app ownership confirmed')}">✓ Verified</span>`:''}</p><p><strong>${e(p.price)}</strong></p><div class="invite-actions project-card-actions"><button class="secondary-button compact-action" data-save-public="${e(p.slug)}">♡ Save</button><a class="primary-button project-details-action" href="/projects/${encodeURIComponent(p.slug)}">View details</a><button class="secondary-button compact-action" data-invite-project="${e(p.slug)}">Share</button></div><p class="cw-meta" data-save-status role="status"></p></div></article>`;}
// Match the homepage discovery card while keeping server-rendered navigation.
export function discoveryCard(p:any){
 const href=`/projects/${encodeURIComponent(p.slug)}`;
 const creator=p.creator?.slug?`<a class="creator-link is-compact" href="/people/${encodeURIComponent(p.creator.slug)}"><strong>${e(p.creator.name)}</strong></a>`:`<span>${e(p.creator?.name||'Independent maker')}</span>`;
 return `<article class="catalog-row future-card"><div class="row-media"><a class="row-preview" href="${href}" aria-label="View ${e(p.name)} details"><img src="${e(p.preview)}" alt="Preview of the ${e(p.name)} website" loading="lazy"></a></div><div class="future-card-heading"><div class="future-card-copy"><a class="row-title" href="${href}">${e(p.name)}</a><p class="future-card-summary">${e(p.summary)}</p><div class="future-card-creator"><span>By</span>${creator}</div><div class="future-card-meta"><span class="future-card-category">${e(p.category)}</span><span class="price-badge">${e(p.price)}</span></div></div></div><div class="future-card-foot"><div class="card-try-actions"><a class="primary-button" href="${href}" aria-label="Explore ${e(p.name)}">Explore app</a></div></div></article>`;
}
export const publicActions=`<script src="/interaction-polish.js" defer></script><script src="/project-view.js" defer></script><script src="/public-comments.js" defer></script><script src="/workspace-ui.js" defer></script><script src="/project-media.js" defer></script><script src="/return-preferences.js" defer></script><script src="/project-actions.js" defer></script><script src="/community-input.js" defer></script><script src="/share-invitation.js" defer></script><script src="/notification-bell.js" defer></script><script src="/account-nav.js" defer></script>`;
