export type VerificationProgress={independent?:boolean;earned:number;creators:number;hasPublished:boolean;ownershipConfirmed:boolean;verified:boolean;caseId:string|null;eligible:boolean};
export async function verificationProgress(db:any,userId:string):Promise<VerificationProgress>{
 const [r,profile]=await Promise.all([db.rpc('cw_badge_progress',{p_user:userId}),db.from('profiles').select('creator_type').eq('user_id',userId).maybeSingle()]);
 if(profile.error||!profile.data)throw Error('Creator type unavailable');const independent=profile.data.creator_type!=='company';
 if(r.error||!r.data?.[0])throw Error('Verification progress unavailable');
 const s=r.data[0],earned=Number(s.reviews),creators=Number(s.creators);
 return {independent,earned,creators,hasPublished:s.has_published,ownershipConfirmed:s.ownership_confirmed,verified:s.verified&&earned>=5&&creators>=3&&s.ownership_confirmed,caseId:s.case_id,eligible:independent&&earned>=5&&creators>=3&&s.has_published};
}
export function verificationCard(s:VerificationProgress){
 if(s.independent===false)return '<section class="cw-panel"><h2>Build with the community</h2><p>Companies are welcome to publish apps, share them and contribute feedback. The earned Verified Creator badge is for independent creators.</p><a class="primary-button" href="/">Browse apps</a></section>';
 const title=s.verified?'You’re a Verified Creator':'Earn your Verified Creator badge';
 return `<section class="cw-panel verification-progress"><p class="eyebrow">Contribute. Build trust.</p><h2>${title}</h2><p>Give five qualifying reviews across at least three other creators, and confirm ownership of your published app.</p><progress class="verification-meter" value="${Math.min(s.earned,5)}" max="5" aria-label="Qualifying reviews">${Math.min(s.earned,5)} of 5</progress><ul class="verification-checklist"><li>${Math.min(s.earned,5)} / 5 qualifying reviews</li><li>${Math.min(s.creators,3)} / 3 other creators</li><li>${s.ownershipConfirmed?'✓ App ownership confirmed':s.hasPublished?'App ownership confirmation needed':'Publish an app to confirm ownership'}</li></ul>${s.verified?'':s.caseId?'<a class="secondary-button" href="/dashboard/help?case='+encodeURIComponent(s.caseId)+'">View your review request</a>':s.eligible?'<a class="primary-button" href="/dashboard/verification">Confirm app ownership</a>':'<a class="primary-button" href="/">Find an app to review</a>'}<p class="cw-meta">Specific, original reviews count after approval. Helpful criticism counts equally. Self-reviews, copied or spam feedback don’t count. This badge recognizes contribution and app ownership; it does not guarantee app quality.</p></section>`;
}
