import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import '../listing-rules.js';
import {normalizeDraft} from '../src/server/listing-policy.mjs';
const source=name=>readFileSync(new URL('../'+name,import.meta.url),'utf8');
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const draftKey='creatorworks-listing-draft-v1';
function drafts(local,session){const c={sessionStorage:session,Date};Object.defineProperty(c,'localStorage',{get(){if(local instanceof Error)throw local;return local;}});c.window=c;vm.runInNewContext(source('listing-storage.js'),c);return c.CWListingStorage;}
test('draft survives same-tab reload/sign-in return with local storage blocked',()=>{const session=storage();const first=drafts(Error('blocked'),session);assert.equal(first.save({url:'https://example.com/',does:'A useful tool'}),true);const restored=drafts(Error('blocked'),session).read();assert.equal(restored.url,'https://example.com/');assert.equal(restored.does,'A useful tool');});
test('old flat drafts remain readable and session fallback wins after local quota failure',()=>{const local=storage(),session=storage();local.setItem(draftKey,JSON.stringify({url:'https://old.example/'}));const api=drafts(local,session);assert.equal(api.read().url,'https://old.example/');local.setItem=()=>{throw Error('quota');};assert.equal(api.save({url:'https://new.example/'}),true);assert.equal(drafts(local,session).read().url,'https://new.example/');api.clear();assert.equal(local.getItem(draftKey),null);assert.equal(session.getItem(draftKey),null);});
test('unavailable storage fails explicitly and malformed storage does not crash recovery',()=>{const bad={getItem:()=>'{bad',setItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}};const api=drafts(Error('blocked'),bad);assert.equal(api.save({url:'https://example.com'}),false);assert.equal(Object.keys(api.read()).length,0);assert.doesNotThrow(()=>api.clear());});
test('client and server agree on 140/500-character boundaries without word limits',()=>{const r=globalThis.CWListingRules;for(const [client,server,max] of [['does','headline',140],['helps','help_text',500],['firstTry','first_try',500]]){assert.equal(r.valid('a'.repeat(max),client),true);assert.equal(r.valid('a'.repeat(max+1),client),false);assert.equal(normalizeDraft({[server]:'a'.repeat(max)}).error,undefined);assert.match(normalizeDraft({[server]:'a'.repeat(max+1)}).error,/characters/);}assert.equal(r.valid('...','does'),false);});
async function analytics(consent,search=''){
 const local=storage();if(consent)local.setItem('cw-analytics-consent',consent);const scripts=[];
 const element=()=>({setAttribute(){},addEventListener(){},append(){},remove(){}});
 const c={URL,URLSearchParams,Date,localStorage:local,location:{pathname:'/',origin:'https://trymybuild.com',hostname:'trymybuild.com',search},document:{referrer:'https://example.com/private?email=secret',cookie:'',querySelector:()=>null,addEventListener(){},createElement:element,head:{append:e=>scripts.push(e)},body:{append(){}}},fetch:async()=>({json:async()=>({measurementId:'G-TEST'})})};c.window=c;vm.runInNewContext(source('analytics.js'),c);await new Promise(resolve=>setImmediate(resolve));return {c,local,scripts,calls:()=>Array.from(c.dataLayer||[],args=>Array.from(args))};
}
const campaign='?utm_source=youtube&utm_medium=paid_video&utm_campaign=trymybuild_launch&utm_content=guys_talking&email=secret&url=https://private.example&gclid=secret';
test('unknown or denied consent never loads Google or queues submission attempts',async()=>{for(const consent of [null,'denied']){const a=await analytics(consent,campaign);a.c.CWAnalytics.urlAttempt(true);assert.equal(a.scripts.length,0);assert.equal(a.calls().length,0);}});
test('approved attribution and attempt events exclude URLs, identity and query strings',async()=>{const a=await analytics('granted',campaign);a.c.CWAnalytics.urlAttempt(true);a.c.CWAnalytics.urlAttempt(false);const calls=a.calls();const config=calls.find(c=>c[0]==='config')[2];assert.equal(config.campaign_content,'guys_talking');assert.equal(config.page_location,'https://trymybuild.com/');assert.equal(config.page_referrer,'https://example.com');const attempts=calls.filter(c=>c[1]==='url_submit_attempt');assert.equal(attempts.length,2);assert.equal(attempts[0][2].validation_result,'valid');assert.equal(attempts[1][2].validation_result,'invalid_url');assert.deepEqual(Object.keys(attempts[0][2]),['validation_result']);assert.doesNotMatch(JSON.stringify(calls),/secret|private\.example|gclid|email=/);a.local.setItem('cw-analytics-consent','denied');a.c.CWAnalytics.urlAttempt(true);assert.equal(a.calls().length,calls.length);});
test('unapproved campaign values never enter Analytics',async()=>{for(const search of [campaign.replace('guys_talking','someone@example.com'),campaign.replace('youtube','private-source')]){const a=await analytics('granted',search);assert.equal(a.calls().find(c=>c[0]==='config')[2].campaign_content,undefined);assert.doesNotMatch(JSON.stringify(a.calls()),/someone@|private-source/);}});

test('fallback stays newest when saves share a millisecond',()=>{const local=storage(),session=storage();const c={window:null,localStorage:local,sessionStorage:session,Date:{now:()=>100}};c.window=c;vm.runInNewContext(source('listing-storage.js'),c);c.CWListingStorage.save({title:'Old'});local.setItem=()=>{throw Error('quota');};c.CWListingStorage.save({title:'New'});assert.equal(drafts(local,session).read().title,'New');});
