import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import{readFile}from'node:fs/promises';
const source=await readFile(new URL('../interaction-polish.js',import.meta.url),'utf8'),joinSource=source.slice(0,source.indexOf(" if(!document.getElementById('app'))"))+'\n})();';
function fixture(context,saveOK=true){
 const storage=new Map([['trymybuild-join-context',JSON.stringify({...context,at:Date.now()})]]),calls=[],listeners=new Map(),body={style:{position:'fixed',top:'-90px'}},profile={scrollTop:0};let catalogReady=false;
 const window={CWPanels:{open:async(path,kind)=>calls.push(['panel',path,kind])},CWOpenProject:slug=>{calls.push(['open',slug]);return catalogReady;},CWSetDetailScroll:(...v)=>calls.push(['scroll',...v]),CWRestoreBrowse:b=>calls.push(['browse',b]),addEventListener:(n,f)=>listeners.set(n,f),dispatchEvent:e=>calls.push(['event',e.type])};
 const scope={window,Date,URL,Event,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},location:{origin:'https://local.invalid',pathname:context.path.split('?')[0]},history:{replaceState:(_a,_b,url)=>calls.push(['url',url.href])},sessionStorage:{getItem:k=>storage.get(k),removeItem:k=>storage.delete(k)},document:{body,querySelector:selector=>selector==='.profile-panel'?profile:null},fetch:async(path,options)=>{calls.push(['request',path,JSON.parse(options.body)]);return{ok:saveOK};}};vm.runInNewContext(joinSource,scope);
 return{join:window.CWJoin,storage,calls,body,profile,ready(){catalogReady=true;listeners.get('cw-catalog-ready')?.();}};
}
test('sign-in resumes a pending save, creator profile and project without losing scroll',async()=>{const f=fixture({action:'save',slug:'sample',project:'sample',profile:'builder',projectInPanel:true,path:'/people/builder',scroll:90,profileScroll:220,projectScroll:140});await f.join.restore({authenticated:true});assert.equal(f.storage.size,0);assert.deepEqual(f.calls.filter(c=>c[0]==='panel'),[['panel','/people/builder','profile'],['panel','/projects/sample','project']]);assert.deepEqual(f.calls.find(c=>c[0]==='request'),['request','/api/saved',{slug:'sample',saved:true}]);assert.equal(f.profile.scrollTop,220);assert.equal(f.body.style.top,'-90px');await f.join.restore({authenticated:true});assert.equal(f.calls.filter(c=>c[0]==='request').length,1);});
test('a catalog arriving after account status restores the detail scroll when it opens',async()=>{const f=fixture({action:'comment',slug:'sample',project:'sample',path:'/',scroll:310,projectScroll:160});await f.join.restore({authenticated:true});f.ready();assert.equal(f.calls.filter(c=>c[0]==='open').length,2);assert.deepEqual(f.calls.at(-1),['scroll',310,160]);assert.equal(f.body.style.top,'-310px');});
test('an unauthenticated return keeps the pending action for joining',async()=>{const f=fixture({action:'save',slug:'sample',path:'/'});await f.join.restore({authenticated:false});assert.equal(f.storage.size,1);assert.equal(f.calls.length,0);});
