import {wishCategories} from '../../server/wish-policy.mjs';
import {OWNED_CARD_FIELDS,performancePanel} from '../../server/dashboard-cards';
import {notificationPreferences,prepareNotifications} from '../../server/notifications';
import type { APIRoute } from 'astro';
import { memberContext, workspace, notice, empty } from '../../server/workspace';
import { signIn, e, unavailable } from '../../server/feedback-ui';
import { randomUUID } from 'node:crypto';

const field=(name:string,value:string)=>`<input type="hidden" name="${name}" value="${e(value)}">`;
const start=(action:string,section:string)=>`<form method="post" action="/api/dashboard">${field('action',action)}${field('section',section)}`;
const check=(name:string,label:string,on:boolean)=>`<label class="cw-choice"><input type="checkbox" name="${name}" ${on?'checked':''}>${label}</label>`;
export const GET:APIRoute=async context=>{
 const section=context.params.section||'';
 if(!['overview','notifications','preferences','privacy','help'].includes(section))return new Response('Not found',{status:404});
 try {
  const m=await memberContext(context);if(!m)return signIn('/dashboard/'+section);
  const {db,member,admin}=m;let body=notice(context),title='',identity:any;
  if(section==='overview'){
   const profile=await db.from('profiles').select('display_name,avatar_path').eq('user_id',member.id).single();if(profile.error)throw Error();
   const first=(m.user.firstName||profile.data.display_name.split(/\s+/)[0]||'there').trim();title=`Welcome to your dashboard, ${first}.`;identity={name:profile.data.display_name,avatar:profile.data.avatar_path||''};
   const results=await Promise.all([db.from('projects').select('id',{head:true,count:'exact'}).eq('owner_user_id',member.id),db.from('saved_projects').select('project_slug',{head:true,count:'exact'}).eq('user_id',member.id),db.from('notifications').select('id',{head:true,count:'exact'}).eq('user_id',member.id).is('read_at',null),db.from('support_cases').select('id',{head:true,count:'exact'}).eq('user_id',member.id).neq('status','resolved')]);
   if(results.some(r=>r.error))throw Error();
   const [projects,comments]=await Promise.all([db.from('projects').select(OWNED_CARD_FIELDS).eq('owner_user_id',member.id).order('updated_at',{ascending:false}).order('id').limit(8),db.rpc('cw_combined_inbox',{p_user:member.id})]);if(projects.error||comments.error)throw Error();
   body+=`<div class="workspace-summary">${results.map((r,i)=>`<a href="${['/dashboard?view=creator','/dashboard?view=visitor','/dashboard/notifications','/dashboard/help'][i]}"><strong>${r.count}</strong><span>${['My projects','Saved projects','Unread notifications','Open requests'][i]}</span></a>`).join('')}<a href="/dashboard/messages"><strong>${Number(comments.data?.[0]?.total_count)||0}</strong><span>Conversations</span></a></div>${performancePanel(projects.data,results[0].count||0)}`;
  }else if(section==='preferences'||section==='notifications'){
   const pref=await db.from('account_preferences').select('*').eq('user_id',member.id).maybeSingle();if(pref.error)throw Error();const p={feedback_alerts:true,publication_alerts:true,tips:true,personalization:true,interests:[],selected_interests:[],...pref.data,...await notificationPreferences(db,member.id)};
   title=section==='preferences'?'Your preferences':'Notifications';
   if(section==='preferences'){
    const learned=await db.from('category_engagement').select('category,clicks').eq('user_id',member.id).order('clicks',{ascending:false}).order('updated_at',{ascending:false}).limit(10);if(learned.error)throw Error();
    body+=`<section class="cw-panel">${start('preferences',section)}<h2>Personalized discovery</h2><p>Choose the categories you care about below. You can also let your browsing activity improve suggestions; it will not change your selected interests.</p>${check('personalization','Use my category activity to personalize suggestions',p.personalization!==false)}${check('tips','Show guidance tips',p.tips)}<fieldset><legend>Your interests · Click as many as you want</legend><div class="interest-options">${wishCategories.map(category=>`<label class="cw-choice"><input type="checkbox" name="interest" value="${e(category)}" ${p.selected_interests.includes(category)?'checked':''}>${e(category)}</label>`).join('')}</div></fieldset><button class="primary-button">Save preferences</button></form></section><section class="cw-panel"><h2>Your learned priorities</h2>${learned.data.length?`<ol class="interest-ranking">${learned.data.map((x:any)=>`<li><span>${e(x.category)}</span><strong>${x.clicks} ${x.clicks===1?'visit':'visits'}</strong></li>`).join('')}</ol>`:'<p class="cw-meta">Open project categories from Browse tools and your priorities will appear here.</p>'}${start('preferences-reset',section)}<button class="secondary-button">Reset category history</button></form></section>`;
   }
   else{
    await prepareNotifications(db,member.id,admin);
    const page=Math.max(0,Math.min(10000,Math.floor(Number(context.url.searchParams.get('page'))||0)));
    const rows=await db.from('notifications').select('*',{count:'exact'}).eq('user_id',member.id).order('created_at',{ascending:false}).order('id').range(page*25,page*25+24);if(rows.error)throw Error();
    body+=`<section class="cw-panel">${start('alerts',section)}<h2>In-app alerts</h2>${check('feedbackAlerts','New feedback and replies',p.feedback_alerts)}${check('publicationAlerts','Project publication updates',p.publication_alerts)}${check('reviewOpportunities','Weekly suggestions of projects to try and review',p.review_opportunities!==false)}${check('savedUpdates','Updates to projects I saved',p.saved_updates!==false)}${check('recommendations','New projects matching my interests',p.recommendations)}${check('activityDigest','Weekly project saves and feedback summary',p.activity_digest)}${check('draftReminders','One reminder for an unfinished draft',p.draft_reminders)}<p class="cw-meta">Summaries are prepared when you visit, at most once per week. Recommendations use your selected interests and, if personalization is enabled, the categories you visit. Manage both in Preferences. Draft reminders appear once after seven days. View counts are not included.</p><p class="cw-meta">Support replies, account safety notices, and contribution or verification decisions always appear here. Email and push notifications are not enabled.</p><button class="secondary-button">Save alert settings</button></form></section>${start('read-all',section)}<button class="secondary-button">Mark all as read</button></form>${rows.data.map(n=>`<article class="cw-panel"><p class="cw-meta">${n.read_at?'Read':'Unread'} · ${e(new Date(n.created_at).toLocaleDateString('en-US'))}</p><a href="${e(n.href.startsWith('/')&&!n.href.startsWith('//')?n.href:'/dashboard')}">${e(n.title)}</a>${!n.read_at?`${start('read',section)}${field('id',n.id)}<button class="cw-link">Mark as read</button></form>`:''}</article>`).join('')||empty('You’re all caught up. New updates will appear here.')}<nav class="cw-row">${page?`<a href="?page=${page-1}">Previous</a>`:''}${(page+1)*25<(rows.count||0)?`<a href="?page=${page+1}">Next</a>`:''}</nav>`;
   }
  }else if(section==='privacy'){
   title='Privacy & your data';body+=`<section class="cw-panel"><h2>Your public identity</h2><p>You control whether your profile is public. Published projects and public contributions can still show your public name.</p><a href="/dashboard/profile">Manage public profile</a></section><section class="cw-panel"><h2>Download your data</h2><p>Export your profile, projects, saved items, preferences, contributions, and support requests as a JSON file.</p><a class="secondary-button" href="/api/account-export">Download my data</a></section><section class="cw-panel"><h2>Optional analytics</h2><p>Analytics is off unless you choose to allow it.</p><button class="secondary-button" data-analytics-settings>Change analytics preference</button><script src="/analytics.js" defer></script></section><section class="cw-panel"><h2>Account deletion</h2><p>Request deletion or check a pending request in your account settings.</p><a href="/dashboard/security">Account & security</a></section><p><a href="/privacy">Read our privacy notice</a></p>`;
  }else{
   title='Help & contact';const id=context.url.searchParams.get('case');
   if(id&&/^[0-9a-f-]{36}$/.test(id)){
    const r=await db.from('support_cases').select('*').eq('id',id).eq('user_id',member.id).maybeSingle();if(r.error)throw Error();if(!r.data)return new Response('Not found',{status:404});const c=r.data;
    const messages=await db.from('support_messages').select('message,is_staff,created_at').eq('case_id',id).order('created_at');if(messages.error)throw Error();
    body+=`<p><a href="/dashboard/help">← All requests</a></p><section class="cw-panel"><p class="cw-meta">${e(c.kind)} · ${e(c.status)}</p><h2>${e(c.subject)}</h2><p class="cw-message">${e(c.message)}</p></section>${messages.data.map(r=>`<section class="cw-panel"><strong>${r.is_staff?'TryMyBuild support':'You'}</strong><p class="cw-message">${e(r.message)}</p></section>`).join('')}<section class="cw-panel">${start('case-reply','help')}${field('id',id)}${field('revision',String(c.revision))}${field('request',randomUUID())}<label for="message">Add a reply</label><textarea name="message" id="message" minlength="1" maxlength="4000" required></textarea><button class="primary-button">Send reply</button></form></section>`;
   }else{
    const rows=await db.from('support_cases').select('id,subject,status,created_at').eq('user_id',member.id).order('created_at',{ascending:false}).limit(100);if(rows.error)throw Error();
    body+=`<section class="cw-panel"><h2>Quick answers</h2><details><summary>Where is my project?</summary><p>Open My projects to continue drafts or view publication status. A draft stays private until you submit it and it is approved.</p></details><details><summary>How do I update a project?</summary><p>Choose Edit in My projects. Changes to public content return the listing to review.</p></details><details><summary>How do I report a problem?</summary><p>Choose a request type below. Include the project name or link and what happened. Never send passwords or payment information.</p></details></section><section class="cw-panel"><h2>Contact TryMyBuild</h2>${start('case-create','help')}${field('id',randomUUID())}<label for="kind">I need help with</label><select name="kind" id="kind">${[['support','General support'],['report','Report abuse or a project'],['copyright','Copyright concern'],['appeal','Appeal a moderation decision'],['verification','Creator verification']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><label for="subject">Subject</label><input name="subject" id="subject" minlength="3" maxlength="120" required><label for="project">Project identifier (optional)</label><input name="project" id="project" pattern="[a-z0-9-]{1,80}" maxlength="80" placeholder="The project’s URL name"><label for="message">How can we help?</label><textarea id="message" name="message" minlength="10" maxlength="4000" required></textarea><p class="cw-meta">For copyright concerns, identify your work, the project involved, and your authority to report it. This starts a review; it is not by itself a complete statutory notice. Replies appear here and in Notifications.</p><button class="primary-button">Send request</button></form></section><h2>My requests</h2>${rows.data.map(r=>`<article class="cw-panel"><a href="?case=${r.id}">${e(r.subject)}</a><p class="cw-meta">${e(r.status)} · ${e(new Date(r.created_at).toLocaleDateString('en-US'))}</p></article>`).join('')||empty('No requests yet.')}`;
   }
  }
  return workspace(title,body,section,admin,identity);
 }catch{return unavailable();}
};
