import {adminNavigation} from '../../server/feedback-ui';
import type { APIRoute } from 'astro';
import { memberContext, workspace, notice } from '../../server/workspace';
import { e, unavailable } from '../../server/feedback-ui';
import { randomUUID } from 'node:crypto';
import { env } from '../../server/auth';
const hidden=(n:string,v:string)=>`<input type="hidden" name="${n}" value="${e(v)}">`;
const form=(action:string,id:string,tab:string)=>`<form method="post" action="/api/admin/manage">${hidden('action',action)}${hidden('id',id)}${hidden('tab',tab)}`;
export const GET:APIRoute=async context=>{
 try{
  const m=await memberContext(context);if(!m?.admin)return new Response('Administrator access required',{status:403});
  const tabs=['overview','people','cases','privacy','activity','settings'];const tab=tabs.includes(context.url.searchParams.get('tab')||'')?context.url.searchParams.get('tab')!:'overview';const {db}=m;
  let body=`<div class="cw-admin-layout">${adminNavigation(tab)}<div class="cw-admin-content">${notice(context)}`;
  if(tab==='overview'){
   const queries=[db.from('users').select('id',{head:true,count:'exact'}).eq('account_status','active'),db.from('projects').select('id',{head:true,count:'exact'}).eq('listing_status','in_review'),db.from('support_cases').select('id',{head:true,count:'exact'}).neq('status','resolved'),db.from('account_deletion_requests').select('user_id',{head:true,count:'exact'}).in('status',['pending','processing'])];const rs=await Promise.all(queries);if(rs.some(r=>r.error))throw Error();
   body+=`<div class="cw-stat-grid">${rs.map((r,i)=>`<a class="cw-panel" href="${['?tab=people','/admin?section=projects','?tab=cases','?tab=privacy'][i]}"><strong>${r.count}</strong><span>${['Active accounts','Listings awaiting review','Open support requests','Deletion requests'][i]}</span></a>`).join('')}</div><p class="cw-meta">These are account and workflow counts, not visitor analytics.</p>`;
  }else if(tab==='people'){
   const q=(context.url.searchParams.get('q')||'').slice(0,60).replace(/[%_]/g,'');let query=db.from('profiles').select('user_id,display_name,slug,verified,users!inner(account_status,workos_user_id,system_role)').neq('users.account_status','deleted').order('display_name').limit(100);if(q)query=query.ilike('display_name','%'+q+'%');const r=await query;if(r.error)throw r.error;
   body+=`<form method="get"><input type="hidden" name="tab" value="people"><label for="q">Find a member by public name</label><input name="q" id="q" value="${e(q)}" maxlength="60"><button class="secondary-button">Search</button></form><p class="cw-meta">Showing up to 100 active or suspended members. Deleted accounts are excluded; audit records remain in Activity. Narrow the search for more specific results.</p>${r.data.map((p:any)=>`<section class="cw-panel"><h2>${e(p.display_name)}</h2><p>${e(p.users.account_status)} · ${p.verified?'Verified creator':'Not verified'}</p><p class="cw-meta">Member ID: ${e(p.user_id)}</p>${p.users.workos_user_id===m.user.id||p.users.system_role==='admin'||p.users.account_status==='deleted'?'<p>Protected account</p>':`${form('member',p.user_id,tab)}${hidden('expected',p.users.account_status)}<label>Action<select name="decision"><option value="${p.users.account_status==='suspended'?'reactivate':'suspend'}">${p.users.account_status==='suspended'?'Restore account access':'Suspend account access'}</option><option value="verify">Approve Verified Creator badge</option><option value="unverify">Remove Verified Creator badge</option></select></label><label>Reason and evidence<input name="reason" minlength="3" maxlength="300" required></label><p class="cw-meta">Approve only after five qualifying reviews across three other creators and app ownership confirmation. Suspension blocks account access; review published content separately.</p><label class="cw-choice"><input name="confirm" type="checkbox" value="yes" required>I reviewed this member and confirm this action.</label><button class="secondary-button">Apply decision</button></form><details class="cw-danger-zone"><summary>Permanently remove this member</summary><p>This redacts the member’s content, removes uploaded previews, and deletes their WorkOS sign-in identity. A minimal audit tombstone remains for system integrity.</p>${form('admin-erase',p.user_id,tab)}<label>Detailed reason<input name="reason" minlength="10" maxlength="300" required></label><label>Type DELETE to confirm<input name="confirmation" pattern="DELETE" required autocomplete="off"></label><p class="cw-meta">Confirm your identity in <a href="/dashboard/security">Account &amp; security</a> immediately before this action.</p><button class="danger-button">Permanently remove member</button></form></details>`}</section>`).join('')}`;
  }else if(tab==='cases'){
   const id=context.url.searchParams.get('case');
   if(id&&/^[0-9a-f-]{36}$/.test(id)){
    const r=await db.from('support_cases').select('*').eq('id',id).single();if(r.error)throw r.error;const c=r.data;
    const reported=c.kind==='report'?String(c.message).match(/^Conversation ([0-9a-f-]{36})(?: · Reply ([0-9a-f-]{36}))?/):null;
    const privateReport=c.kind==='report'?String(c.message).match(/^Private conversation ([0-9a-f-]{36})/):null;
    if(privateReport){
     const page=Math.max(0,Math.min(10000,Number(context.url.searchParams.get('messagesPage'))||0));
     const thread=await db.from('direct_threads').select('id,member_a,member_b').eq('id',privateReport[1]).maybeSingle();if(thread.error)throw thread.error;
     if(thread.data&&[thread.data.member_a,thread.data.member_b].includes(c.user_id)){
      const messages=await db.from('direct_messages').select('sender_id,message,created_at',{count:'exact'}).eq('thread_id',thread.data.id).order('created_at',{ascending:false}).order('id').range(page*25,page*25+24);if(messages.error)throw messages.error;
      body+=`<section class="cw-panel"><h2>Reported private conversation</h2><p>Private evidence for this report only. Criticism alone is not abuse.</p>${messages.data.map(message=>`<article class="cw-reply"><small>${e(message.sender_id===c.user_id?'Reporter':'Other participant')} · ${e(message.created_at)}</small><p class="cw-message">${e(message.message)}</p></article>`).join('')}<nav>${page?`<a href="?tab=cases&amp;case=${id}&amp;messagesPage=${page-1}">Newer</a>`:''}${(page+1)*25<(messages.count||0)?`<a href="?tab=cases&amp;case=${id}&amp;messagesPage=${page+1}">Older</a>`:''}</nav></section>`;
     }
    }
    if(reported){
     const review=await db.from('creator_feedback').select('id,author_user_id,project_slug,message').eq('id',reported[1]).maybeSingle();if(review.error)throw review.error;
     const owner=review.data?await db.from('projects').select('owner_user_id').eq('slug',review.data.project_slug).maybeSingle():{data:null,error:null};if(owner.error)throw owner.error;
     if(review.data&&(c.user_id===review.data.author_user_id||c.user_id===owner.data?.owner_user_id)){
      const qualification=await db.from('feedback_qualifications').select('status,reason,revision').eq('feedback_id',reported[1]).maybeSingle();if(qualification.error)throw qualification.error;
      let evidence=review.data.message;
      if(reported[2]){const reply=await db.from('feedback_replies').select('message').eq('id',reported[2]).eq('feedback_id',reported[1]).maybeSingle();if(reply.error)throw reply.error;evidence=reply.data?.message||'Reply unavailable';}
      body+=`<section class="cw-panel"><h2>Reported ${reported[2]?'reply':'feedback'}</h2><p class="cw-message">${e(evidence)}</p><p>Private evidence for this report. A negative opinion alone is not grounds for action.</p>${qualification.data?`<form method="post" action="/api/admin/community-review">${hidden('kind','credit')}${hidden('id',reported[1])}${hidden('revision',String(qualification.data.revision))}<p>Credit status: ${e(qualification.data.status)}</p><label>Credit decision<select name="status"><option value="qualified">Keep or restore the qualifying credit</option><option value="revoked">Revoke an invalid reward</option><option value="rejected">Reject an ineligible review</option></select></label><label>Reason<input name="reason" minlength="3" maxlength="300" required></label><button class="secondary-button">Save credit decision</button></form>`:''}</section>`;
     }
    }
    const replies=await db.from('support_messages').select('message,is_staff,created_at').eq('case_id',id).order('created_at');if(replies.error)throw replies.error;
    body+=`<section class="cw-panel"><p>${e(c.kind)} · ${e(c.status)}</p><h2>${e(c.subject)}</h2><p class="cw-meta">Member ${e(c.user_id)}${c.project_slug?' · Project '+e(c.project_slug):''}</p><p class="cw-message">${e(c.message)}</p></section>${replies.data.map(r=>`<section class="cw-panel"><strong>${r.is_staff?'Support':'Member'}</strong><p class="cw-message">${e(r.message)}</p></section>`).join('')}<section class="cw-panel">${form('reply',id,tab)}${hidden('request',randomUUID())}${hidden('revision',String(c.revision))}<label>Reply to this member<textarea name="message" maxlength="4000" required></textarea></label><label>Status<select name="status"><option value="waiting">Waiting for member</option><option value="open">Open</option><option value="resolved">Resolved</option></select></label><button class="primary-button">Send reply & update status</button></form></section>`;
   }else{
    const status=['open','waiting','resolved'].includes(context.url.searchParams.get('status')||'')?context.url.searchParams.get('status')!:'open';const r=await db.from('support_cases').select('id,subject,kind,status,created_at').eq('status',status).order('created_at').limit(100);if(r.error)throw r.error;
    body+=`<nav class="cw-subnav">${['open','waiting','resolved'].map(t=>`<a href="?tab=cases&status=${t}">${t}</a>`).join('')}</nav>${r.data.map(c=>`<section class="cw-panel"><p>${e(c.kind)} · ${e(c.status)}</p><a href="?tab=cases&case=${c.id}">${e(c.subject)}</a></section>`).join('')||'<p>No requests in this queue.</p>'}`;
   }
  }else if(tab==='privacy'){
   const jobs=await db.from('erasure_jobs').select('user_id,created_at').eq('status','pending').order('created_at');if(jobs.error)throw jobs.error;
   body+=jobs.data.map(job=>`<section class="cw-panel"><h2>Removed account · cleanup unfinished</h2><p>The account cannot sign in. Storage or identity-provider cleanup still needs to finish.</p><p class="cw-meta">Member ${e(job.user_id)}</p>${form('retry-erasure',job.user_id,tab)}<label>Type DELETE to retry cleanup<input name="confirmation" pattern="DELETE" required></label><p>Confirm your identity in <a href="/dashboard/security">Account &amp; security</a> first.</p><button class="secondary-button">Retry cleanup</button></form></section>`).join('');
   const r=await db.from('account_deletion_requests').select('user_id,status,requested_at,erasure_consent').in('status',['pending','processing']).order('requested_at');if(r.error)throw r.error;
   body+=`<p>Deletion removes the member’s public profile, unpublishes and redacts their projects, redacts their contributions, clears saved data, removes uploaded previews, and deletes their sign-in identity. Other participants’ contributions and necessary audit records remain.</p>${r.data.map(x=>`<section class="cw-panel"><h2>Account deletion request</h2><p>Member ${e(x.user_id)} · ${e(x.status)}</p>${x.erasure_consent?`${form('erase',x.user_id,tab)}<label>Type DELETE to complete the member’s requested deletion<input name="confirmation" pattern="DELETE" required autocomplete="off"></label><p class="cw-meta">Confirm your identity in <a href="/dashboard/security">Account & security</a> first, then return here. External cleanup can be retried if interrupted.</p><button class="secondary-button">Complete requested deletion</button></form>`:'<p>This earlier request asked for a review only. The member must confirm the deletion plan in Account & security before it can be completed.</p>'}</section>`).join('')||'<p>No pending deletion requests.</p>'}`;
  }else if(tab==='activity'){
   const r=await db.from('operations_log').select('action,reason,target_id,created_at').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;
   body+=`<p><a href="/admin?section=activity">Project and community moderation history →</a></p><div class="cw-table-wrap"><table><thead><tr><th>When</th><th>Action</th><th>Reason</th></tr></thead><tbody>${r.data.map(x=>`<tr><td>${e(new Date(x.created_at).toLocaleString('en-US'))}</td><td>${e(x.action)}</td><td>${e(x.reason)}</td></tr>`).join('')}</tbody></table></div><p>Latest 100 account and support actions.</p>`;
  }else{
   body+=`<section class="cw-panel"><h2>Service connections</h2><p>Authentication: ${env('WORKOS_API_KEY')?'Configured':'Not configured'}</p><p>Database: ${env('SUPABASE_SERVICE_ROLE_KEY')?'Configured':'Not configured'}</p><p>Google Analytics: ${/^G-[A-Z0-9]+$/.test(env('GOOGLE_ANALYTICS_MEASUREMENT_ID'))?'Configured; visitors must opt in':'Not activated'}</p><a href="https://analytics.google.com/" target="_blank" rel="noopener">Open Google Analytics ↗</a><p class="cw-meta">Service credentials are managed in hosting settings and never exposed here. Analytics does not measure private dashboard activity. Age and gender reporting are not enabled.</p></section><section class="cw-panel"><h2>Catalog & publication</h2><p>Categories come from published projects. Assign a category in project settings. Public listings are sorted newest first.</p><a href="/admin?section=projects">Review project categories and submissions</a></section><section class="cw-panel"><h2>Policies</h2><p>The public policies are available throughout the site and from account creation.</p><p><a href="/terms">Terms of Service</a> · <a href="/privacy">Privacy Policy</a></p></section>`;
  }
  body+='</div></div>';
  return workspace('Administration',body,'overview',true);
 }catch{return unavailable();}
};
